name: walkytalky
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  permission_handler: ^10.2.0 
  shared_preferences: ^2.4.0
  loading_animation_widget:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
flutter_icons:
  android: true 
  ios: false    
  image_path: "assets/logo/logo.png" 